version: "3.9"

services:
  java_app:
    container_name: java_app
    image: pee-java_app:1.0.0
    build: .
    ports:
      - 8762:8762
    environment:
      - DATABASE_URL=jdbc:sqlserver://java_db:1433;databaseName=postgres?createDatabaseIfNotExist=true
      - DATABASE_USERNAME=sa
      - DATABASE_PASSWORD=980Parace12tamol%&
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 14033:1433
    environment:
      ACCEPT_EULA: Y
      SA_USER: sa
      SA_PASSWORD: 980Parace12tamol%&
      SA_DB: postgres